package service

import (
	"sort"
	"time"

	"orcaarch/internal/domain"
	"orcaarch/internal/mock"
)

type ProcessingResult struct {
	Reconciliations []domain.ReconciliationResult
	LandedCosts     map[string]domain.Money       // key: tracking_number
	WACBySKU        map[string]domain.Money       // key: sku_id, final blended WAC
	LedgerEntries   []domain.LedgerEntry
	Quarantine      []domain.Quarantine
	Reprocessed     *domain.ReprocessingOutput    // nil if no DISCREPANCY exists
}

// Process runs the full in-memory pipeline for n shipments generated by mock.Generate.
func Process(n int) (ProcessingResult, error) {
	erps, invoices := mock.Generate(n)

	erpByTN := make(map[string]domain.ERPShipment, len(erps))
	for _, e := range erps {
		erpByTN[e.TrackingNumber] = e
	}
	invByTN := make(map[string]domain.CarrierInvoice, len(invoices))
	for _, c := range invoices {
		invByTN[c.TrackingNumber] = c
	}

	results := domain.Reconcile(erps, invoices, 50)

	landedCosts := make(map[string]domain.Money)
	var quarantine []domain.Quarantine

	for _, r := range results {
		switch r.Status {
		case domain.StatusMatched, domain.StatusDiscrepancy:
			inv := invByTN[r.TrackingNumber]
			lc, err := domain.CalculateLandedCost(domain.LandedCostInput{
				FactoryCostUSD:   domain.MustMoney(0, "USD"),
				ActualFreightUSD: inv.ActualFreightCurrency,
				CustomsDutiesUSD: inv.CustomsDutiesLocal,
				AncillaryFeesUSD: inv.AncillaryFeesUSD,
				InsuranceCostUSD: inv.InsuranceCostUSD,
			})
			if err != nil {
				return ProcessingResult{}, err
			}
			landedCosts[r.TrackingNumber] = lc
		case domain.StatusUnreconciledERP:
			erp := erpByTN[r.TrackingNumber]
			lc, err := domain.CalculateLandedCost(domain.ProvisionalLandedCostInput(erp))
			if err != nil {
				return ProcessingResult{}, err
			}
			landedCosts[r.TrackingNumber] = lc
		case domain.StatusUnreconciledCarrier:
			inv := invByTN[r.TrackingNumber]
			quarantine = append(quarantine, domain.NewQuarantine(inv))
		}
	}

	// WAC per SKU: accumulate in trade_date order; UNRECONCILED_CARRIER has no ERP → skip.
	type wacItem struct {
		tradeDate time.Time
		weight    int64
		lc        domain.Money
	}
	groups := make(map[string][]wacItem)
	for _, r := range results {
		if r.Status == domain.StatusUnreconciledCarrier {
			continue
		}
		lc, ok := landedCosts[r.TrackingNumber]
		if !ok {
			continue
		}
		erp := erpByTN[r.TrackingNumber]
		groups[erp.SKUID] = append(groups[erp.SKUID], wacItem{
			tradeDate: erp.TradeDate,
			weight:    erp.TotalWeightMilliTons,
			lc:        lc,
		})
	}

	wacBySKU := make(map[string]domain.Money)
	for sku, items := range groups {
		sort.Slice(items, func(i, j int) bool {
			return items[i].tradeDate.Before(items[j].tradeDate)
		})
		oldStock := int64(0)
		oldWAC := domain.MustMoney(0, "USD")
		for _, item := range items {
			wac, err := domain.CalculateWAC(domain.WACInput{
				OldStockMilliTons:    oldStock,
				OldWACPerMilliTon:    oldWAC,
				NewShipmentMilliTons: item.weight,
				NewLandedCostUSD:     item.lc,
			})
			if err != nil {
				return ProcessingResult{}, err
			}
			oldStock += item.weight
			oldWAC = wac
		}
		wacBySKU[sku] = oldWAC
	}

	var ledgerEntries []domain.LedgerEntry
	for _, r := range results {
		entries, err := domain.GenerateLedgerEntries(r)
		if err != nil {
			return ProcessingResult{}, err
		}
		ledgerEntries = append(ledgerEntries, entries...)
	}

	// Reprocessing demo: correct first DISCREPANCY by setting carrier freight = ERP estimated.
	var reprocessed *domain.ReprocessingOutput
	for _, r := range results {
		if r.Status != domain.StatusDiscrepancy {
			continue
		}
		erp := erpByTN[r.TrackingNumber]
		corrected := invByTN[r.TrackingNumber]
		corrected.ActualFreightCurrency = erp.EstimatedFreightUSD

		var origEntries []domain.LedgerEntry
		for _, e := range ledgerEntries {
			if e.TrackingNumber == r.TrackingNumber {
				origEntries = append(origEntries, e)
			}
		}

		out, err := domain.Reprocess(domain.ReprocessingInput{
			Original:    r,
			OrigEntries: origEntries,
			NewInvoice:  corrected,
			ERP:         erp,
			ToleranceBP: 50,
		})
		if err != nil {
			return ProcessingResult{}, err
		}

		ledgerEntries = append(ledgerEntries, out.Reversals...)
		ledgerEntries = append(ledgerEntries, out.NewEntries...)
		reprocessed = &out
		break
	}

	return ProcessingResult{
		Reconciliations: results,
		LandedCosts:     landedCosts,
		WACBySKU:        wacBySKU,
		LedgerEntries:   ledgerEntries,
		Quarantine:      quarantine,
		Reprocessed:     reprocessed,
	}, nil
}
